### ISSUE TITLE
Make processing handler states more consistent with message selection states

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceInsight#525]
We allow selecting messages via processing handlers but the UI states for processing handlers is not consistent with that for message labels. 

So the processing handlers should be use following combined hover and active states:

![2015-11-30 at 10 37](https://cloud.githubusercontent.com/assets/493451/11468320/d784f194-974e-11e5-811c-2b3913aef1ce.png)

**Comment by HEskandari** [comment]
had a look at this today...is not trivial as though it is. We currently don't show the 'route arrow' on mouse hover, so that's a functional change as the trigger is currently activated on mouse hover (because route arrow, handler and message box are three different elements). We can do it for the selected state though as that is just change in color in the state that we already have the items in.

**Comment by distantcam** [comment]
Fixed

**Comment by sergioc** [comment]
@distantcam I played with the latest build and it didn't seem quite there yet. 

For your reference, I created a quick prototype to demonstrate the idea here: https://dl.dropboxusercontent.com/u/664957/si-525/index.html (note that it'll only work with the `LoanDecisionResponseReceived` and `AnotherMessage` messages).

**Comment by johnsimons** [comment]
@distantcam is looks like the hover arrow zindex is not top most too, see
![image](https://cloud.githubusercontent.com/assets/122651/11550113/279689e8-99b8-11e5-81c2-e329736057b1.png)

**Comment by johnsimons** [comment]
@sergioc see image above, what would the highiligting color be for handlers in error ? It doesn't look right to highlight it in blue also, thougths ?

**Comment by sergioc** [comment]
Good point @johnsimons. I've updated [the prototype](https://dl.dropboxusercontent.com/u/664957/si-525/index.html) to include a failed processing handler. Let me know what you think.

**Comment by sergioc** [comment]
@distantcam The arrow that connects the message label to its processing handler currently only shows when you hover the message name. 

That arrow and the message label hover state should also show when hovering on the processing handler (in addition to showing the tooltip). 

The [updated prototype](https://dl.dropboxusercontent.com/u/664957/si-525/index.html) should give a clear idea of how should it work when you hover only the message label or when you hover the processing handler.

**Comment by johnsimons** [comment]
That looks good to me @sergioc 

@distantcam can you finish this touch ups today ?

**Comment by distantcam** [comment]
@sergioc I've pushed a potential fix for this. Could you please verify it now works the way you expect, and if so close this issue.

**Comment by HEskandari** [comment]
@distantcam looks like the ZIndex is still an issue when doing mouse-over:

![image](https://cloud.githubusercontent.com/assets/132117/11619369/40658848-9cfb-11e5-92e6-61f876f7b994.png)

**Comment by distantcam** [comment]
I actually prefer it that way ;) But I'll go change it to be over not under.

**Comment by HEskandari** [comment]
Think this can be closed now.

**Comment by sergioc** [comment]
Only missing having the processing icon also blue in the selected state.
