### ISSUE TITLE
Show tooltips when hovering the different elements in the sequence diagram

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceInsight#528]
Add tooltip to message arrow lines to allow user to understand what does the line type (solid or dashed) signifies.

Suggested text format: `MessageName command` and `MessageName event`.

**Comment by sergioc** [comment]
@johnsimons this issue is still valid and it should take precedence over https://github.com/Particular/ServiceInsight/issues/523, since it's more probably it gives the results we want (understanding the diagram) and implementation cost is possibly lower. Also, tooltips as a way to explore the meaning of graphic elements in a UI is a long standing pattern, and users are used to/expect being able to do that.

**Comment by sergioc** [comment]
See the following preview for an idea of how to present tooltips (only works with messages `CommandMsgE`,`CommandMsgFReallyLongMessageTypeName
WillNotFitIntoOneLineAsYouCanSee` or `CommandMsgG`)

https://dl.dropboxusercontent.com/u/664957/si-525/index.html

A couple of additional notes:
- For messages (arrow and label) I think ideally the tootip should show above the hovered element, and aligned with the mouse cursor. This is to ensure the tooltip is visible if only a segment of the arrow is visible on screen. I didn't have time to prototype this today.
- For handlers, the message should ideally not show on top of the vertical arrow that connects the handler with the message. This allows the user to have full visibility of all relationships at the same time the tooltip shows.
- A delay for the tooltip will be needed (I used 500ms) to avoid tooltips showing prematurely when users are just dancing around with the mouse cursor.

**Comment by HEskandari** [comment]
@sergioc regarding two points here, wouldn't that be better if we leave positioning, and more importantly, timing to OS to manage? I don't think there's any way to manage time anyway and there's limited functionality to control the position as well.

In other words tooltips will appear where OS places them, in the time that is consistent with the overall behavior of the OS.

**Comment by HEskandari** [comment]
@sergioc having said all that, I have implemented the tooltip for the arrow/line/message. See if this is good enough. The position it appears in is in the top center of the arrow 'object'. The object includes the Message box, the arrow head and the line.

**Comment by sergioc** [comment]
@HEskandari I tested with shrinked viewports, and although it doesn't show exactly where the mouse cursor is, the tool tip still shows fully. I think we're good to go for message tooltips.

**Comment by sergioc** [comment]
@HEskandari seems like all that is left to do here is to improve the tooltips for the handlers.

**Comment by HEskandari** [comment]
@sergioc checked out the prototype, do you think it'd suffice if we display the handler tooltip on the opposite site of the arrow (so that it doesn't overlap)?

**Comment by sergioc** [comment]
@HEskandari you mean under the handler?

**Comment by sergioc** [comment]
@HEskandari can you use `#b3b3b3` color for properties text (not title) in the tooltip to improve contrast?

Also, I've updated the tooltip placement for `CommandMsgG`'s handler - is that what you mean? If yes, I think that's a reasonable trade-off for easier implementation.

**Comment by HEskandari** [comment]
@sergioc I have moved it to under the handler, added the callout arrow, changed the colors based on your prototype (white for values and title, `#b3b3b3` for property keys and made the title bold. This is done across all tooltips (endpoint, message/line/arrow and handler). See if this is good enough.

![image](https://cloud.githubusercontent.com/assets/132117/11706062/83ee06a8-9f49-11e5-91c4-b123da02d12b.png)

**Comment by sergioc** [comment]
Awesome!

**Comment by sergioc** [comment]
Due to some confusion about the meaning of handlers vs. processing during testing, we need to replace the current processing tooltips' titles from "Processing Handler" to "Processing of message".
